language: java
jdk:
#  - openjdk6
#  - oraclejdk7
  - oraclejdk8
#  - openjdk7

sudo: false

before_install:
  - mvn install -DskipTests=true -e

script:
  - mvn test -X

after_success:
  - mvn clean

branches:
  only:
    - master

notifications:
  email:
    - bschlining@gmail.com
