/*
 * SearchPanel.java
 *
 * Created on May 12, 2006, 9:35 AM
 */

package mbarix4j.swing;

/**
 *
 * @author  brian
 */
public class SearchPanel extends javax.swing.JPanel {
    
    /**
     * 
     */
    private static final long serialVersionUID = -641011699894722892L;
    /** Creates new form SearchPanel */
    public SearchPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        nameTf = new javax.swing.JTextField();
        globCb = new javax.swing.JCheckBox();
        searchBtn = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        add(nameTf);

        globCb.setText("Glob");
        globCb.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        globCb.setMargin(new java.awt.Insets(0, 4, 0, 4));
        add(globCb);

        add(searchBtn);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
	 * @uml.property  name="globCb"
	 * @uml.associationEnd  multiplicity="(1 1)"
	 */
    private javax.swing.JCheckBox globCb;
    /**
	 * @uml.property  name="nameTf"
	 * @uml.associationEnd  multiplicity="(1 1)"
	 */
    private javax.swing.JTextField nameTf;
    /**
	 * @uml.property  name="searchBtn"
	 * @uml.associationEnd  multiplicity="(1 1)"
	 */
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
    
}
